{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"text":"description","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time."}],"hierarchy":{"paths":[["doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError"]]},"metadata":{"externalID":"s:12IScribeAISDK0A2AIC25ClientAuthenticationErrorO08internalF0yAESS_tcAEmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"text":"description","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"IScribeAISDK"}],"symbolKind":"case","roleHeading":"Case","title":"IScribeAI.ClientAuthenticationError.internalError(description:)"},"kind":"symbol","references":{"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK":{"abstract":[{"text":"iScribe AI eliminates the burden of medical documentation, giving providers back time and energy to reinvest in their patients and their own wellbeing.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This iOS SDK provides direct access to the iScribe AI service. Simply record audio for a providerâ€™s session with a patient and submit. Our service will then auto-generate high quality medical documentation based on the content of that recording."}],"type":"topic","title":"IScribeAISDK","kind":"symbol","role":"collection","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","url":"\/documentation\/iscribeaisdk"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI":{"kind":"symbol","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","type":"topic","role":"symbol","title":"IScribeAI","url":"\/documentation\/iscribeaisdk\/iscribeai","abstract":[{"text":"This singleton is the primary interaction point for clients of the SDK. It handles starting and stopping recording as well as submitting recordings for processing and iScribe AI summary generation.","type":"text"}],"navigatorTitle":[{"text":"IScribeAI","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IScribeAI","kind":"identifier"}]},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError/internalError(description:)":{"role":"symbol","abstract":[{"text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"description","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","kind":"symbol","title":"IScribeAI.ClientAuthenticationError.internalError(description:)","url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError","abstract":[{"text":"An error that may occur while attempting to authenticate the provided JWT token.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ClientAuthenticationError","kind":"identifier"}],"type":"topic","title":"IScribeAI.ClientAuthenticationError","navigatorTitle":[{"text":"ClientAuthenticationError","kind":"identifier"}],"url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror"}}}