{"abstract":[{"text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError"]]},"metadata":{"externalID":"s:12IScribeAISDK0A2AIC25ClientAuthenticationErrorO08internalF0yAESS_tcAEmF","roleHeading":"Case","modules":[{"name":"IScribeAISDK"}],"symbolKind":"case","title":"IScribeAI.ClientAuthenticationError.internalError(description:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"description","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)"},"references":{"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK":{"type":"topic","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","role":"collection","title":"IScribeAISDK","kind":"symbol","url":"\/documentation\/iscribeaisdk","abstract":[{"text":"iScribe AI eliminates the burden of medical documentation, giving providers back time and energy to reinvest in their patients and their own wellbeing.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This iOS SDK provides direct access to the iScribe AI service. Simply record audio for a providerâ€™s session with a patient and submit. Our service will then auto-generate high quality medical documentation based on the content of that recording."}]},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError":{"type":"topic","kind":"symbol","url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ClientAuthenticationError"}],"abstract":[{"type":"text","text":"An error that may occur while attempting to authenticate the provided JWT token."}],"title":"IScribeAI.ClientAuthenticationError","navigatorTitle":[{"text":"ClientAuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI":{"url":"\/documentation\/iscribeaisdk\/iscribeai","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IScribeAI","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"IScribeAI","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"This singleton is the primary interaction point for clients of the SDK. It handles starting and stopping recording as well as submitting recordings for processing and iScribe AI summary generation."}],"title":"IScribeAI","type":"topic"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError/internalError(description:)":{"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)","abstract":[{"text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time.","type":"text"}],"identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","title":"IScribeAI.ClientAuthenticationError.internalError(description:)"}}}