{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)"]}],"hierarchy":{"paths":[["doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError"]]},"metadata":{"externalID":"s:12IScribeAISDK0A2AIC25ClientAuthenticationErrorO08internalF0yAESS_tcAEmF","symbolKind":"case","roleHeading":"Case","title":"IScribeAI.ClientAuthenticationError.internalError(description:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"IScribeAISDK"}]},"abstract":[{"type":"text","text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK":{"abstract":[{"text":"iScribe AI eliminates the burden of medical documentation, giving providers back time and energy to reinvest in their patients and their own wellbeing.","type":"text"},{"type":"text","text":" "},{"text":"This iOS SDK provides direct access to the iScribe AI service. Simply record audio for a providerâ€™s session with a patient and submit. Our service will then auto-generate high quality medical documentation based on the content of that recording.","type":"text"}],"type":"topic","kind":"symbol","title":"IScribeAISDK","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","role":"collection","url":"\/documentation\/iscribeaisdk"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IScribeAI","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/iscribeaisdk\/iscribeai","abstract":[{"type":"text","text":"This singleton is the primary interaction point for clients of the SDK. It handles starting and stopping recording as well as submitting recordings for processing and iScribe AI summary generation."}],"title":"IScribeAI","kind":"symbol","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","navigatorTitle":[{"text":"IScribeAI","kind":"identifier"}]},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError/internalError(description:)":{"abstract":[{"text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time.","type":"text"}],"kind":"symbol","title":"IScribeAI.ClientAuthenticationError.internalError(description:)","url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClientAuthenticationError","kind":"identifier"}],"url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror","abstract":[{"type":"text","text":"An error that may occur while attempting to authenticate the provided JWT token."}],"role":"symbol","title":"IScribeAI.ClientAuthenticationError","navigatorTitle":[{"kind":"identifier","text":"ClientAuthenticationError"}],"identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError","type":"topic"}}}